<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPoNcnVx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPoNcnVx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPoNcnVx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPoNcnVx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPoNcnVx\App_KernelDevDebugContainer([
    'container.build_hash' => 'PoNcnVx',
    'container.build_id' => 'c3b8c32c',
    'container.build_time' => 1599205921,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPoNcnVx');
